baseurl = "http://androcetus.com"
languageCode = "en-us"
title = "Androcetus"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

builddrafts = false
canonifyurls = true

[indexes]
category = "categories"

[taxonomies]
series = "series"
category = "categories"

[permalinks]
post = "/:section/:slug"
